### ISSUE TITLE
Add a brief summary of the project

### ISSUE THREAD

**Issue by adalsa91** [adalsa91/tfg#12]

**Comment by JJ** [comment]
If you are going to do it in English, please double check everything before you submit it.

**Comment by adalsa91** [comment]
I always do it and even then I make mistakes... But I'm studying for english qualification and I thought it would be a good idea to practice here.

**Comment by JJ** [comment]
English should always have a capital E :-)

**Comment by JJ** [comment]
Come this point, this should have been addressed or closed...

**Comment by adalsa91** [comment]
Me refería al README del proyecto que ya está hecho, debería de haber sido más concreto y además se me olvidó cerrarlo.
