### ISSUE TITLE
Bibliografía y estado del arte.

### ISSUE THREAD

**Issue by JJ** [adalsa91/tfg#19]
Hay una buena cantidad de profesores de ATC trabajando en este mismo tema, como seguramente sabrás. Como te caiga alguien en el tribunal te puede caer la del pulpo. Así que
1. Tienes que incluir bibliografía
2. Tienes que comentarla y añadir una sección estado del arte donde hable de ella.

Mira [este artículo](https://www.sciencedirect.com/science/article/abs/pii/S0167739X16306604), los que referencia, y los que lo referencia, y también el artículo de Alba de la Universidad de Málaga que tiene que estar ahí y otros.

**Comment by adalsa91** [comment]
De hecho si hay un capítulo de estado del arte con su correspondiente bibliografía, en este menciono los proyectos SIPESCA, PETRA y MOSOS aunque tal vez no he profundizado demasiado, voy a revisar los artículos que mencionas y ampliaré el capítulo.

**Comment by JJ** [comment]
Pero no los artículos publicados
