### ISSUE TITLE
Los objetivos deben ser concretos

### ISSUE THREAD

**Issue by JJ** [adalsa91/tfg#20]
"bajo coste" no es un objetivo; debes tener un coste concreto, o relativo a otros dispositivos, por ejemplo los que te te he mencionado en la bibliografía.

El objetivo secundario tampoco debe ser secundario, y tampoco es un objetivo. El objetivo debería ser para lo que desarrollas ese servidor; relacionado con la motivación, pero más concreto: quiero un dispositivo de bajo coste que capture datos que se puedan visualizar y consultar mediante un API. Para ese objetivo desarrollas el sevidor, pero el objetivo *no* es el servidor. Será el servidor si esa es la mejor opción para lograr ese objetivo (otras opciones podían ser almacenarlos en la nube, por ejemplo)

**Comment by adalsa91** [comment]
Se que "bajo coste" es un poco ambiguo pero intento matizarlo durante el desarrollo del proyecto, en el estado del arte concluyo que se busca una solución más ecónomica que la Raspberry Pi, para más adelante fijar un coste de 15€ en el análisis de requisitos del sensor, ¿debería especificar la cantidad ya en los objetivos?

Respecto al objetivo secundario, lo traté como secundario en la memoría ya que en la descripción inical del proyecto solo se mencionaba el desarrollo de un detector que abratará el coste pero no se hacía mención a la recolección y visualización de estas detecciones, en principio este objetivo nació como un apoyo al objetivo principal pero al final terminó ocupando incluso más tiempo así que me parece que tiene razón en que no es secundario, lo modificaré.

Por otra parte, se que en el objetivo no debería de aparecer la solución, fue un error en el planteamiento inicial, debería de haberme planteado como objetivo como centralizar esos datos y como consultarlos para después analizar posibles soluciones pero en su momento erroneamente me pareció obvio que debería realizarse así y por eso lo consideré directamente como un objetivo y no realizé un buen análisis de otras soluciones, más tarde descubrí alternativas cloud como ThingSpeak pero ya era demasiado tarde para virar. Francamente no sé como tratar esto en la memoria, en las conclusiones he hecho una reflexión sobre los errores que he cometido al no realizar un correcto analisis inicial, lo único que se me ocurre es concretar este error también en esa sección.
