### ISSUE TITLE
Un TFG no es un manual de un producto, es una crónica de desarrollo de un proyecto

### ISSUE THREAD

**Issue by JJ** [adalsa91/tfg#21]
Lo importante es documentar las decisiones que se hayan tomado. Un manual de instalación puede estar en el repositorio (porque es un proyecto real) pero no forma parte de la documentación del tfg, porque el tribunal no va a instalarlo.

**Comment by adalsa91** [comment]
No estaba seguro de si incluirlo pero miré otros TFGs de su repo _TF-libres-UGR_ y ví que lo incluian como anexo así que decidí hacer lo mismo, entonces, ¿me recomienda eliminar ese anexo?

**Comment by JJ** [comment]
@adalsa91 Lo puedes poner como anexo o simplemente como parte del repo. Como veas.
