### ISSUE TITLE
Tratar de evitar relleno en la memoria

### ISSUE THREAD

**Issue by JJ** [adalsa91/tfg#24]
¿De veras que es necesaria una imagen del pinout del ESP32? ¿Eso ayuda a evaluar tu trabajo de qué manera?

**Comment by adalsa91** [comment]
Pues la verdad es que tenía dudas cuando la añadí, pero tenía la sensación de que tenía una documentación muy escueta así que decedí añadirla, pero tiene razón no aporta valor. Voy a eliminarla y revisar otros casos parecidos como el issue #22.
