### ISSUE TITLE
Add support for ssd1306 oled display

### ISSUE THREAD

**Issue by adalsa91** [adalsa91/tfg#6]
- [Adafruit library for ssd1306 repository](https://github.com/mcauser/Adafruit_SSD1306/tree/esp8266-64x48)
[Example](https://github.com/mcauser/Adafruit_SSD1306/blob/esp8266-64x48/examples/ssd1306_64x48_i2c/ssd1306_64x48_i2c.ino)

- [Squix library fot ssd1306 repository](https://github.com/squix78/esp8266-oled-ssd1306)
[Examples](https://github.com/squix78/esp8266-oled-ssd1306/tree/master/examples)

**Comment by JJ** [comment]
So no OLED display? Is this really part of the promiscuous mode?

**Comment by adalsa91** [comment]
No, la verdad es que no era un objetivo del proyecto y me di cuenta de que no aportaba mucho valor así que lo descarté, simplemente había adquirido una pantalla OLED y me pase de optimista.
